/**
 * Environment loading for the Transmat API server.
 *
 * Defaults are the ones in docs/CONTRACT.md and must run with ZERO cloud
 * credentials: `local` storage + `console` push.
 *
 * The one hard requirement is TRANSMAT_TOKEN. In development we never crash
 * over it: if no .env file exists we mint a dev token, persist it, and print
 * it. In production (NODE_ENV=production) a missing token is fatal.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

export const SERVER_ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
export const REPO_ROOT = path.resolve(SERVER_ROOT, '..');

/** Hard caps from the contract. */
export const MAX_FILE_BYTES = 2 * 1024 * 1024 * 1024; // 2 GB
export const MAX_TEXT_BYTES = 64 * 1024; // 64 KB
export const BLOB_URL_TTL_SECONDS = 300; // 5 minutes
// Uploads get longer than downloads: a share extension hands the transfer to
// nsurlsessiond, which may sit on it for a while on a bad network before the
// bytes actually move. Too short and a legitimate background upload 403s.
export const UPLOAD_URL_TTL_SECONDS = 3600; // 1 hour
// How long a transfer may sit in 'uploading' before the janitor reclaims it.
export const UPLOAD_DEADLINE_MS = 6 * 60 * 60 * 1000; // 6 hours
/**
 * How many transfers may sit in 'uploading' at once, across the whole server.
 *
 * A reservation costs nothing to make and buys the holder up to `size` bytes of
 * storage for UPLOAD_DEADLINE_MS, invisible to GET /v1/transfers. Without a
 * ceiling, a client (or a leaked token) can park 6 hours' worth of disk with a
 * loop. This is deliberately generous — a share extension has one upload in
 * flight, not sixty-four.
 */
export const MAX_INFLIGHT_UPLOADS = 64;

/**
 * Metadata that ends up in a response header has to fit in one, and must not
 * be able to contain one. Both of these are attacker-supplied on the presigned
 * path: `mime_type` is echoed as Content-Type and `file_name` as
 * Content-Disposition on GET /blob/:key.
 */
export const MAX_MIME_TYPE_CHARS = 255;
export const MAX_FILE_NAME_CHARS = 1024;

/** RFC 9110 media type: type/subtype plus optional parameters, no controls. */
const MIME_RE = /^[A-Za-z0-9!#$%&'*+.^_`|~-]+\/[A-Za-z0-9!#$%&'*+.^_`|~-]+(?:[ \t]*;[\x20-\x7e]*)?$/;

/** @returns {boolean} */
export function isValidMimeType(value) {
  return (
    typeof value === 'string' &&
    value.length > 0 &&
    value.length <= MAX_MIME_TYPE_CHARS &&
    MIME_RE.test(value)
  );
}

/**
 * Nothing that is not a multipart file part may be unbounded. A JSON transfer
 * body is a 64 KB text payload plus a little envelope; a device registration is
 * a name and a push token. These are the ceilings for those.
 */
export const MAX_JSON_BODY_BYTES = MAX_TEXT_BYTES + 16 * 1024; // 80 KB
export const MAX_DEVICE_BODY_BYTES = 16 * 1024; // 16 KB
export const MAX_DEVICE_NAME_CHARS = 200;
export const MAX_PUSH_TOKEN_CHARS = 512;

export const PLATFORMS = ['ios', 'android', 'macos', 'web', 'cli'];
export const KINDS = ['file', 'text', 'link'];
export const TRANSFER_STATES = ['complete', 'revoked', 'expired'];
export const DELIVERY_STATES = ['pending', 'pushed', 'downloaded'];

const ENV_TEMPLATE = (token) => `# Transmat — generated by the API server on first run.
# This file is gitignored. Copy the token into your clients.
PORT=8787
TRANSMAT_TOKEN=${token}
DATA_DIR=./.data
STORAGE_DRIVER=local
PUSH_DRIVER=console
# BLOB_SIGNING_SECRET=          # defaults to TRANSMAT_TOKEN
# PUBLIC_BASE_URL=              # defaults to http://localhost:$PORT

# --- Cloudflare R2 (only needed when STORAGE_DRIVER=r2) ---
# R2_ACCOUNT_ID=
# R2_ACCESS_KEY_ID=
# R2_SECRET_ACCESS_KEY=
# R2_BUCKET=transmat

# --- APNs (only needed when PUSH_DRIVER=apns) ---
# APNS_KEY_PATH=./secrets/AuthKey_XXXXXXXX.p8
# APNS_KEY_ID=
# APNS_TEAM_ID=
# APNS_BUNDLE_ID=com.example.transmat
# APNS_ENV=sandbox
`;

/**
 * Minimal .env parser. No dependency, handles `export`, comments, quotes.
 * @param {string} source
 * @returns {Record<string,string>}
 */
export function parseEnv(source) {
  /** @type {Record<string,string>} */
  const out = {};
  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    let key = line.slice(0, eq).trim();
    if (key.startsWith('export ')) key = key.slice(7).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"') && value.length > 1) ||
      (value.startsWith("'") && value.endsWith("'") && value.length > 1)
    ) {
      value = value.slice(1, -1);
    } else {
      const hash = value.indexOf(' #');
      if (hash !== -1) value = value.slice(0, hash).trim();
    }
    out[key] = value;
  }
  return out;
}

/**
 * .env locations, least specific first. They are merged in this order, so a
 * repo-root .env can hold the token every component shares while server/.env
 * (or the real process environment) overrides it.
 */
function envCandidates(override) {
  const list = override ?? [
    path.join(REPO_ROOT, '.env'),
    path.join(SERVER_ROOT, '.env'),
    path.join(process.cwd(), '.env'),
  ];
  return list.filter((p, i, all) => all.indexOf(p) === i);
}

function generateToken() {
  return `dev_${crypto.randomBytes(24).toString('base64url')}`;
}

const TRUE_ISH = new Set(['1', 'true', 'yes', 'on']);

/**
 * @typedef {ReturnType<typeof loadConfig>} Config
 */

/**
 * Build the config object.
 * @param {object} [options]
 * @param {Record<string,string|undefined>} [options.env] base environment (defaults to process.env)
 * @param {Record<string,string|undefined>} [options.overrides] wins over everything, for tests
 * @param {boolean} [options.quiet] suppress the generated-token banner
 * @param {string[]} [options.envFiles] override the .env search path (tests)
 */
export function loadConfig(options = {}) {
  const baseEnv = options.env ?? process.env;
  const overrides = options.overrides ?? {};

  /** @type {Record<string,string|undefined>} */
  let env = { ...baseEnv };
  let envFilePath = null;
  let generatedToken = null;

  /** @type {Record<string,string>} */
  let fromFiles = {};
  for (const candidate of envCandidates(options.envFiles)) {
    if (!fs.existsSync(candidate)) continue;
    envFilePath = candidate; // most specific existing file wins as the write target
    fromFiles = { ...fromFiles, ...parseEnv(fs.readFileSync(candidate, 'utf8')) };
  }
  // Real process env wins over any file, as everyone expects.
  env = { ...fromFiles, ...baseEnv, ...overrides };

  const nodeEnv = env.NODE_ENV ?? 'development';
  const isProduction = nodeEnv === 'production';

  let token = (env.TRANSMAT_TOKEN ?? '').trim();
  if (!token) {
    if (isProduction) {
      throw new Error(
        'TRANSMAT_TOKEN is required. Refusing to start in production without it. ' +
          'Set it in the environment or in a .env file.',
      );
    }
    token = generateToken();
    generatedToken = token;
    if (!envFilePath) {
      // No .env at all: create one so the token survives restarts.
      const target = options.envFiles?.at(-1) ?? path.join(SERVER_ROOT, '.env');
      try {
        fs.writeFileSync(target, ENV_TEMPLATE(token), { mode: 0o600, flag: 'wx' });
        envFilePath = target;
      } catch {
        /* read-only fs (tests, containers) — keep the in-memory token */
      }
    } else {
      // .env exists but has no token: append rather than die.
      try {
        fs.appendFileSync(envFilePath, `\nTRANSMAT_TOKEN=${token}\n`);
      } catch {
        /* ignore */
      }
    }
  }

  const port = Number.parseInt(env.PORT ?? '8787', 10) || 8787;
  const dataDir = path.resolve(process.cwd(), env.DATA_DIR ?? './.data');

  const storageDriver = (env.STORAGE_DRIVER ?? 'local').trim().toLowerCase();
  if (storageDriver !== 'local' && storageDriver !== 'r2') {
    throw new Error(`STORAGE_DRIVER must be "local" or "r2" (got "${storageDriver}")`);
  }
  const pushDriver = (env.PUSH_DRIVER ?? 'console').trim().toLowerCase();
  if (pushDriver !== 'console' && pushDriver !== 'apns') {
    throw new Error(`PUSH_DRIVER must be "console" or "apns" (got "${pushDriver}")`);
  }

  const config = {
    nodeEnv,
    isProduction,
    port,
    host: env.HOST ?? '0.0.0.0',
    token,
    generatedToken,
    envFilePath,
    dataDir,
    blobDir: path.join(dataDir, 'blobs'),
    dbPath: env.DB_PATH ? path.resolve(process.cwd(), env.DB_PATH) : path.join(dataDir, 'transmat.db'),
    storageDriver: /** @type {'local'|'r2'} */ (storageDriver),
    pushDriver: /** @type {'console'|'apns'} */ (pushDriver),
    blobSigningSecret: (env.BLOB_SIGNING_SECRET ?? '').trim() || token,
    publicBaseUrl: (env.PUBLIC_BASE_URL ?? '').trim().replace(/\/+$/, '') || `http://localhost:${port}`,
    version: env.TRANSMAT_VERSION ?? '0.1.0',
    defaultExpiryDays: 7,
    sweepIntervalMs: Number.parseInt(env.SWEEP_INTERVAL_MS ?? '60000', 10) || 60000,
    logRequests: TRUE_ISH.has((env.LOG_REQUESTS ?? 'true').toLowerCase()),
    r2: {
      accountId: env.R2_ACCOUNT_ID ?? '',
      accessKeyId: env.R2_ACCESS_KEY_ID ?? '',
      secretAccessKey: env.R2_SECRET_ACCESS_KEY ?? '',
      bucket: env.R2_BUCKET ?? '',
      endpoint: env.R2_ENDPOINT ?? '',
    },
    apns: {
      keyPath: env.APNS_KEY_PATH ?? '',
      keyId: env.APNS_KEY_ID ?? '',
      teamId: env.APNS_TEAM_ID ?? '',
      bundleId: env.APNS_BUNDLE_ID ?? '',
      env: (env.APNS_ENV ?? 'sandbox').toLowerCase() === 'production' ? 'production' : 'sandbox',
      // Apple has exactly two hosts; this override exists so the driver can be
      // pointed at a local HTTP/2 server in tests.
      host: env.APNS_HOST ?? '',
    },
  };

  if (config.storageDriver === 'r2') {
    const missing = ['accountId', 'accessKeyId', 'secretAccessKey', 'bucket'].filter(
      (k) => !config.r2[k],
    );
    if (missing.length && !config.r2.endpoint) {
      throw new Error(
        `STORAGE_DRIVER=r2 needs R2_${missing.map((m) => m.replace(/[A-Z]/g, (c) => '_' + c).toUpperCase()).join(', R2_')}`,
      );
    }
  }
  if (config.pushDriver === 'apns') {
    const missing = ['keyPath', 'keyId', 'teamId', 'bundleId'].filter((k) => !config.apns[k]);
    if (missing.length) {
      throw new Error(`PUSH_DRIVER=apns needs APNS_${missing.join(', APNS_').toUpperCase()}`);
    }
  }

  if (generatedToken && !options.quiet) {
    printGeneratedToken(config);
  }

  return config;
}

function printGeneratedToken(config) {
  const line = '─'.repeat(64);
  process.stdout.write(
    `\n${line}\n` +
      `  No TRANSMAT_TOKEN found — generated a development token.\n` +
      (config.envFilePath ? `  Saved to: ${config.envFilePath}\n` : `  (could not write .env; token lives for this process only)\n`) +
      `\n  TRANSMAT_TOKEN=${config.token}\n\n` +
      `  Use it as:  Authorization: Bearer ${config.token}\n` +
      `${line}\n\n`,
  );
}

export default loadConfig;
